### ISSUE TITLE
Computing unscaled rays

### ISSUE THREAD

**Issue by arindamrc** [fuy34/planerecover#12]
Hi, 

I have a doubt regarding the computation of unscaled rays https://github.com/fuy34/planerecover/blob/3cbba0a6db9d722ece827ea0f3b1dbcb609ca5f9/RecoverPlane.py#L76. You do it inside scale loop and within the 'compute_loss' scope. The intrinsic parameters and the size for all images are equal. Wouldn't it be more efficient to have the unscaled rays pre-computed only once for each scale before starting the training loop?

**Comment by fuy34** [comment]
Yes, for SYNTHIA, all the intrinsic are the same. You are welcome to pre-define the intrinsic or even hard-code one to improve efficiency. But as it is just a small txt file with 16 numbers, I will expect a very limited performance gain.
