### ISSUE TITLE
Generate 3d error

### ISSUE THREAD

**Issue by Karthikaddagadderamesh** [fuy34/planerecover#13]
Hello,
I was able to run the test script and obtain the result
But when i run generate 3D.py i get the following error

Traceback (most recent call last):
  File "generate3D.py", line 134, in <module>
    main()
  File "generate3D.py", line 118, in main
    depth = cv2.imread(depth_file_list[idx], cv2.IMREAD_ANYCOLOR | cv2.IMREAD_ANYDEPTH)/100.
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'

Please let me know if there is a something wrong.

**Comment by Karthikaddagadderamesh** [comment]
I had missed '/' while giving the depth resulkt directory

**Comment by Karthikaddagadderamesh** [comment]
I hhave run the command for generate3d 
 python2 generate3D.py --dataset="/media/Passport/Thesis/Plane_Recover_SYN_data/" --pred_depth="/home/planerecover/result/depth/" --savepath="/home/planerecover/3d_map" --test_list="/home/planerecover/data_pre_processing/SYNTHIA/tst_100.txt" --use_preprocessed=true


I get the following error:
  File "generate3D.py", line 134, in <module>
    main()
  File "generate3D.py", line 115, in main
    img = pil.open(test_files_list[idx])
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 2548, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: '/media/uie02161/Passport/Thesis/Plane_Recover_SYN_data/22/000118.jpg'

**Comment by Karthikaddagadderamesh** [comment]
I removed 1 22 seq from tst_100 to make the generate 3d.py run

**Comment by fuy34** [comment]
Congrats, as we state on README, we intentionally remove seq 22 in our training dataset to see how the model works on an entirely unknown sequence. We later provided the link to download seq.22, but feel free to remove it. It will not have a big influence on the evaluation result.   :)

**Comment by Karthikaddagadderamesh** [comment]
Thank you.. i will close the issue..
