### ISSUE TITLE
Image resolution

### ISSUE THREAD

**Issue by Karthikaddagadderamesh** [fuy34/planerecover#14]
Hello,

I would like to train the model on higher resolution images. Why is the synthia dataset images reduced to low resolution. ANy specific reason.

**Comment by fuy34** [comment]
Hey, 

We follow the SfMLearner's pipeline. The main motivation is to reduce the GPU memory cost and train quickly. The side effect could include enlarging the input receptive field (so we do not need a deep network to see the global information) but also lose some details. 

It would be nice to use a large resolution and see if there is any performance gain.

**Comment by Karthikaddagadderamesh** [comment]
Thank you..
