### ISSUE TITLE
Evaluation doubt

### ISSUE THREAD

**Issue by Karthikaddagadderamesh** [fuy34/planerecover#15]
Hello @fuy34 ,

In the paper for evaluation you have used depth + model_fitting . You have mention you have selected the best 5 planes. On what criteria were the best planes selected(Eg: Number of inliers, area threshold, least RMSE error)

Thanks in advance

**Comment by fuy34** [comment]
Hi, 

If I remember correctly, for the default model, we set the number of planes (to predict) as 5, i.e. our model only predicts at most 5 planes. We use the predicted plane's segmentation and plane parameters to generate the depth map and compare it with the ground truth during evaluation. 

Thanks.
