### ISSUE TITLE
Camera cordinate

### ISSUE THREAD

**Issue by Karthikaddagadderamesh** [fuy34/planerecover#17]
Hello,

I am correctly working with your paper on plane recover with my own dataset. I had a query regarding the camera coordinate system. Since I am using my own dataset my camera coordinate system is X faces front, Y faces left, Z faces up for my depth. I wanted to know the camera coordinate system used if you could remember. This information would be very helpful for 3D reconstruction and prediction.
I believe the pred of the plane parameter is only based on the rgb image. But the calculation of the depth uses the camera coordinates. Does this influence the training. If i am able to get depth in homogenous for my dataset should I change the points to X as left Y as up and Z outward from my camera

**Comment by fuy34** [comment]
Hi，

In this work, we build the depth map using this function, which corresponding to Eq. 2 in our paper. https://github.com/fuy34/planerecover/blob/3cbba0a6db9d722ece827ea0f3b1dbcb609ca5f9/utils.py#L92

It follows the common single view camera coordinate system, where X is rightward, Y is downward, and Z faces outside of the image (depth direction). This will only affect the intrinsic in Eq.2. Therefore, I feel, at least in theory,  as long as you have the right intrinsic, there is no need to adjust the coordinate system. But I am not sure if, in practice, it will influence the fine-tuning accuracy or not.  I hope it helps.

**Comment by Karthikaddagadderamesh** [comment]
Thank you . This information is helpful. :)
