### ISSUE TITLE
J-Linkage

### ISSUE THREAD

**Issue by RuslanOm** [fuy34/planerecover#18]
Hi! Thanks for a great job!

Can you share your implementation of J-Linkage algorithm, mentioned in paper, please?

Thanks!

**Comment by fuy34** [comment]
Hi @RuslanOm,
Sorry for the late reply. 

I adopt the code from the following link. It should be easy for you to modify the code from there. The main modification is to read the depth map from the disk and project pixels to the 3D space using ```P = lambda * K^{-1} * q```, where ```P``` is the 3D point, ```lambda``` is the depth, ```K``` is the camera intrinsic, and ```q``` is the 2D coordinate of the pixels. 

J-Linkage:  http://www.diegm.uniud.it/fusiello/demo/jlk/
RansaCov: http://www.diegm.uniud.it/fusiello/demo/cov/
