### ISSUE TITLE
Assessment link questions

### ISSUE THREAD

**Issue by DING606** [fuy34/planerecover#19]
Thank you for your valuable work!How do you get the .mat in the eval_planes.m file?

 label_all = load(fullfile(label_path, [ ID, '-planes.mat']));

**Comment by fuy34** [comment]
hey, sorry for the late reply. Did not check this repo. frequently. 

I manually label the ground truth. Essentially, we can annotate each planar region with polygons as we mentioned in the paper, and the corresponding 3D points of the labeled pixels can be fitted into planes with the least square algorithm.

**Comment by DING606** [comment]
thanks to your apply ,and i want to know do you have any script code that is easy to generate,thanks!

**Comment by fuy34** [comment]
Yeah, for academic usage, you can send me an email, and I will share the code with you. It is on MATLAB.
