### ISSUE TITLE
Key depth_net/mask/segm1/biases not found in checkpoint

### ISSUE THREAD

**Issue by KrugarMiner** [fuy34/planerecover#2]
When i'm trying to test the algorithm with your pre trained model i get this error. From my understanding in this subject (which is not much) the problem is in the checkpoint files where some variables were not saved in those checkpoints. Can you provide correct checkpoint files? Or have a solution for the problem without the need to train the model from scratch? thanks in advance.

**Comment by fuy34** [comment]
Thanks for your interest in our work and informing the bug. 
It actually due to a typo of the scope name in 'net.py'. I have fixed it. Please update your local version, and the code should work fine now.

**Comment by KrugarMiner** [comment]
Thanks you for the fast reply
