### ISSUE TITLE
missing sequence

### ISSUE THREAD

**Issue by Huangying-Zhan** [fuy34/planerecover#4]
Hi @fuy34 , I think sequence 22 is missing in your shared dataset. There is a sample in `tst_100.txt` which is in sequence 22. However, sequence 22 is not in the shared zip file.

**Comment by fuy34** [comment]
Sorry for the late reply. I am crazily busy this week. Here is a link to download the Seq.22 
https://psu.box.com/s/9rpxfa8zasy95ia5u0ol0wxm6qj9i7s8

It is original data without any pre-processing. We excluded this sequence from the training data to test the sequential performance of the algorithm. It looked good based on our experiment (although we did not cover it on the paper). Have fun with it. :)
