### ISSUE TITLE
Test the pre-trained model without the ground truth depth map

### ISSUE THREAD

**Issue by HenryJunW** [fuy34/planerecover#6]
Impressive work. I am wondering whether i can test the pretrained model without the ground truth depth map. Since in the code test_SYNTHIA.py, we need to specify the path to the ground truth depth map, however, if we don't have the ground truth depth map, can we still do the plane parameters estimation? Thanks.

**Comment by fuy34** [comment]
Hi, 
Sorry for the late reply. In this project, we estimate the plane parameters by reconstruct the 3D scene with the predicted planes and comparing it with the ground truth depth. Ideally, if the plane parameters are correctly predicted, then the reconstructed 3D scene should have a similar depth map with ground truth. 

Of course, we can estimate the plane parameters in different ways, e.g. comparing it with the ground truth plane parameters (if applicable), or simply visualizing the reconstructed scene to estimate its correctness.  Both of them should be easily achieved by  small modification of the test code. 

I hope it helps. Thanks.
