### ISSUE TITLE
Problem when trying to fine-tune

### ISSUE THREAD

**Issue by KrugarMiner** [fuy34/planerecover#7]
Hi!!
I noticed that when i try to fine-tune your model with more data it fails to load the initial checkpoint file. Is there any bug or undocumented way to fine tune properly? Thanks in advance.

**Comment by fuy34** [comment]
Hi, 
May I ask if you have set the ```continue_train``` option to ```True```, and set the ```init_checkpoint_file``` path correctly ? 
If you already did that, please let me know your implementation environment, so I can reproduce this error and try to figure out the reason.  I have never met this problem before.  Thanks.
