### ISSUE TITLE
Cityscapes 

### ISSUE THREAD

**Issue by waychin-weiqin** [fuy34/planerecover#8]
Hi, 

In your paper you mentioned you have used CityScapes dataset as well. By any chance can you share the dataset? 

Thank you

**Comment by fuy34** [comment]
Hi, 
We do use the CityScape dataset, but I am not sure if we can share it, as we are not clear about their license and they require to first register an account to download their dataset. 

If you would like to use this dataset, my suggestion is to first register an account on https://www.cityscapes-dataset.com and then download ```leftImg8bit_trainvaltest.zip```, ```gtFine_trainvaltest.zip``` and ```disparity_trainvaltest.zip ```. Then with a simple modification of our pre-processing and data-loading code, you should be able to fine-tuning our model on this dataset. 

Thank you.

**Comment by waychin-weiqin** [comment]
Thank you for your reply. I will try that out. 

I have another question regarding KITTI dataset. Is it possible to use the sparse disparity ground truth from KITTI as the depth ground truth in your work? 

Thank you in advance

**Comment by fuy34** [comment]
We tried on KITTI dataset before. There is no problem for sparse depth ground truth.

But if I remember correctly, KITTI only has a very limited number (< 500) of images with third-party semantic annotation at that time.  We found our model cannot transfer well with such limited training data. I am not sure if there are more annotated images nowadays.

**Comment by waychin-weiqin** [comment]
There are only 200 images for training in term of KITTI. I am planning to do some learning on other bigger dataset like the one you have used in your work then fine tuned it on KITTI later on. 

Thank you for your swift reply :)

**Comment by fuy34** [comment]
Yeah, this strategy maybe work. 

Another way I just realized is that you can also mix the KITTI data with other datasets, and maybe balance the weight of the data during the training (e.g. giving more weight to KITTI data if you are interested in it). Please let me know if you can make the model works on KITTI :).
